# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b0d5a56f7017efcdb8df6635c07a9c04416ec3333ab57a5c71086f254d0682f8e0005b906db3c0669a75a18111b118dc73c7ce2133cefeb419ae7ed30d138d6

test:
  secret_key_base: b4edef9760ab434431c2302ec66292101ef7263594ebb4bd8ad04e73f7031d78d3ef101b4afa1838dd93c9314e9ef883e554007789a689fffd8ea07642dcf71d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
